const APP_KEY = "YOUR_TWITTER_APP_KEY";
const APP_SECRET = "YOUR_TWITTER_APP_SECRET";
const ACCESS_TOKEN = "YOUR_TWITTER_ACCESS_TOKEN";
const ACCESS_SECRET = "YOUR_TWITTER_ACCESS_SECRET";
const OPENAI_API_KEY = "YOUR_OPENAI_API_KEY"; // Используем OpenAI вместо Gemini

const SECRETS = {
  APP_KEY,
  APP_SECRET,
  ACCESS_TOKEN,
  ACCESS_SECRET,
  OPENAI_API_KEY, // Обновленный ключ API
};

module.exports = SECRETS;
